(define/contract (merge-triplets triplets target)
  (-> (listof (listof exact-integer?)) (listof exact-integer?) boolean?)
     (and
      (ormap (lambda (triplet) (and (= (first triplet) (first target))
                                    (<= (second triplet) (second target))
                                    (<= (third triplet) (third target))
                                    )
               )
             triplets
             )
      (ormap (lambda (triplet) (and (<= (first triplet) (first target))
                                    (= (second triplet) (second target))
                                    (<= (third triplet) (third target))
                                    )
               )
             triplets
             )
      (ormap (lambda (triplet) (and (<= (first triplet) (first target))
                                    (<= (second triplet) (second target))
                                    (= (third triplet) (third target))
                                    )
               )
             triplets
             )
      )
  )
